version: "2"

volumes:
    db:

services:
    db:
        image: bitnami/postgresql:14.1.0-debian-10-r31
        ports:
            - 5432:5432
        volumes:
            - db:/bitnami/postgresql
            - ./back-web-bde/database/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRESQL_USER=webbde
            - POSTGRESQL_PASSWORD=webbde
            - POSTGRESQL_DATABASE=webbde
    back:
        image: webbde-back
        ports:
            - 4000:4000
        environment:
            - DATABASE_URI=postgresql://webbde:webbde@web-bde_db_1:5432/webbde
            - JWT_TOKEN=secrettoken
            - JWT_EXPIRATION=30d
    front:
        image: webbde-front
        ports:
            - 3000:3000
        environment:
            - API_URL=http://web-bde_back_1:4000
