name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "40 22 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This Issue had no activity for 60, it was labeled as inactive"
          stale-pr-message: "This Pull Request had no activity for 60, it was labeled as inactive"
          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"
          close-issue-label: "closed-issue"
          close-pr-label: "closed-pr"
          days-before-stale: 60
          days-before-close: 7
